#!/usr/bin/env python

import RPi.GPIO as GPIO

# use P1 header pin numbering convention
GPIO.setmode(GPIO.BOARD)

in_ports=[38,40,37,35]
out_ports=[3,5,7,8]

# Set up the GPIO channels - one input and one output
for i in in_ports:
	GPIO.setup(i, GPIO.IN)

for i in out_ports:
	GPIO.setup(i, GPIO.OUT)

try:
	while True:
		for i in range(4):
			input_value = GPIO.input(in_ports[i])
			print([input_value, in_ports[i]])
			GPIO.output(out_ports[i], input_value==1)

				

except KeyboardInterrupt:
	GPIO.cleanup()
	print "Bye"
			

