#!/usr/bin/env python

import sys
import select
import time


print("She bang!")




def something(line):
  print('read input:', line)

def something_else():
  print('no input')

while True:

  time.sleep(1)

# If there's input ready, do something, else do something
# else. Note timeout is zero so select won't block at all.
  while sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
    line = sys.stdin.readline()
    if line:
      something(line)
    else: # an empty line means stdin has been closed
      print('eof')
      exit(0)
  else:
    something_else()

