#!/usr/bin/env python

import sys
import socket
import fcntl, os
import errno
import time


TCP_IP = '192.168.178.54'
TCP_PORT = 23
BUFFER_SIZE = 20  # Normally 1024, but we want fast response
print('A1')


s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

s.bind((TCP_IP, TCP_PORT))
s.listen(1)
print('A2')

conn, addr = s.accept()
conn.settimeout(1)


print 'Connection address:', addr
while 1:
    try:
        data = conn.recv(BUFFER_SIZE)
    except conn.timeout:
        print("Fuck")

    if data:
        print "received data:", data
        #conn.send(data)  # echo
    
    time.sleep(2)
    print('A3')
conn.close()
